# -----------------------------------------------------------------------------
# Build workflow for PlinkProxy
# Author: Urs Roesch https://github.com/uroesch
# Version: 0.3.0
# -----------------------------------------------------------------------------
name: build-release

on:
  push:
    branches:
    - workflow/*
  pull_request:
    branches:
    - master
    - main
  workfow_dispatch:

jobs:
  build-package:
    timeout-minutes: 15
    runs-on: windows-latest

    steps:
    - name: Download and install AutoIt
      shell: bash
      run: |
        curl --location -o autoit-v3.zip \
          "https://www.autoitscript.com/cgi-bin/getfile.pl?autoit3/autoit-v3.zip"
        7z x -y autoit-v3.zip

    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        lfs: true

    - name: Run build script
      shell: cmd
      run: cmd/CompilePlinkProxy.cmd
      timeout-minutes: 5
